ceph/ceph-deploy

README.rst

Update doc to remove reference to ceph-extras for RPM and DEB
repos. ceph-deploy is no longer pushed to the ceph-extras repo
and hasn't been for some time. If users are not installing from
PyPI, they should be using either the testing or release repo
of their choice for ceph.

doc: update README to not install from ceph-extras

---

ceph-deploy.spec

This pull request fixes two types of rpmlint warnings in the ceph-deploy RPM packaging.
The first commit changes the tabs to spaces in the `ceph-deploy.spec` file.
The second commit quotes the RPM macros in the comments of `ceph-deploy.spec`.

rpmlint fixes

---

ceph_deploy/hosts/fedora/install.py
ceph_deploy/hosts/remotes.py
docs/source/install.rst

Since Fedora ships downstream RPMs that obsolete
python-ceph, those RPMs will be pulled in to resolve
dependencies instead of those hosted by ceph.com, leading
to package errors.
To prevent this, enable check_obsoletes in the Yum
priorities plugin.
Fixes: 10476

Enable check_obsoletes in Fedora

---

ceph-deploy.spec

The `%{pyver}` RPM macro is not present on Red Hat-based systems. It was removed for SUSE as a part of commit 83070c14f1682e3b6eb7f45f43ba6afda6f026a4. This pull request removes it for RHEL also.
This fixes a problem where `rpm -qp --requires ceph-deploy-1.5.21-0.noarch.rpm` would show that the binary RPM literally required `python >= %{pyver}`, since RPM did not interpolate the macro to any value.

ceph-deploy.spec: remove %{pyver} references

---

ceph_deploy/hosts/centos/install.py

We previously enabled this Yum plugin config flag for Fedora, but
recent changes in the EPEL packaging make it necessary for CentOS
and RHEL (when using upstream packages) as well.

Enable check_obsoletes for CentOS and RHEL

---

ceph_deploy/cli.py
ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/rhel/__init__.py
ceph_deploy/hosts/rhel/install.py
ceph_deploy/hosts/rhel/mon/__init__.py
ceph_deploy/hosts/rhel/mon/create.py
ceph_deploy/hosts/rhel/pkg.py
ceph_deploy/hosts/rhel/uninstall.py
ceph_deploy/install.py
ceph_deploy/tests/test_install.py

this adds a bit on top of @trhoden work by adding a namespace attribute that tells if a user explicitly asked for a ceph release or not.
This "check for a default and change otherwise" logic will enable us to enforce a behavior where a user in a RHEL system to use the RHEL packages *by default* unless it is specifying otherwise.
Some of the changes are temporary, since this is just to address the immediate need to support split Ceph packages.

rhel repo support

---

ceph_deploy/install.py

The output from running "ice_setup" instructs users to run "ceph-deploy install --repo {hosts}".
That command would fail because it was not loading the RHEL host module when it needed to (it used the centos module).

Detect RHEL/RHCEPH for 'install --repo'

---

ceph_deploy/hosts/fedora/uninstall.py

Quick workaround but at least it allows purge and purgedata to work
on Fedora 21.
See http://tracker.ceph.com/issues/10928

Try to remove also ceph-common on Fedora.

---

ceph_deploy/mds.py
ceph_deploy/osd.py
ceph_deploy/rgw.py

Removes unimplemented commands from the argument parser.
Confusing to users to see options that you can't actually use.  :)
Ref: http://tracker.ceph.com/issues/11118

Remove destroy

---

docs/source/changelog.rst
docs/source/conf.py
docs/source/contents.rst
docs/source/install.rst
docs/source/mds.rst
docs/source/mon.rst
docs/source/new.rst
docs/source/pkg.rst
docs/source/rgw.rst

This make several updates to the docs:
* adds new pages for mds and rgw
* changes the layout of the changelog a bit to make things cleaner/easier to navigate
* fixes some section level mistakes (moving sections up one, down one as far a nesting goes)
* adds release dates in the changelog
All builds and displays correctly for me locally.

ceph-deploy doc additions and rework

---

ceph_deploy/mon.py
ceph_deploy/osd.py
ceph_deploy/tests/test_mon.py

To get monitor members feature will be reuse serval times in mon.py and osd.py.
Due to this reason, I rewrite the helper function for this feature.
If you have any questions, feel free to let me know.
Thanks!
Signed-off-by: Vicente Cheng <freeze.bilsted@gmail.com>

Add abstracted get initial monitor member function

---

ceph_deploy/gatherkeys.py
ceph_deploy/new.py

Reported in https://bugzilla.suse.com/show_bug.cgi?id=920926
by  Andreas Stieger <astieger@suse.com>
Before thsi fix to umask for keyring handling, After execution
of ceph-deploy, all keyrings have mode 644.
The documented ceph-deploy procedure by creating a dedicated
admin user, and keys will be readable to all other (non-admin)
users as well, thus leaking authentication credentials.
The fix uses umask to resolve the writing of keyfiles.

Fix: keyring permissions where world readable

---

MANIFEST.in

Include tox.ini in sdist tarball.
Ref: http://tracker.ceph.com/issues/11242

11242 include tox.ini

---

ceph_deploy/install.py

The for loop was always returning after the first host
Ref: http://tracker.ceph.com/issues/11273
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1198326

make install --repo handle multiple hosts

---

vendor.py

Hey guys,
Ran into an issue where the ./bootstrap script used to configure ceph-deploy was trying to pull down a remoto git repo from ceph.com. Updated to direct to Alfredo's remoto repo (heh). I tested this myself, but let me know if there's something I misunderstood. I also took this opportunity to switch to https:// instead of git://...https is much more reliable behind a proxy.
Joe

Updating the url used to clone the remoto repository

---

docs/source/changelog.rst

One of the changes in ceph-deploy 1.5.23 is tracked as CVE-2015-3010. Document this in the changelog.

doc: add CVE-2015-3010 to changelog

---

docs/source/changelog.rst
setup.py

That fixes a problem where output would be cut before closing the connection.
Reference issue: http://tracker.ceph.com/issues/11347

use new remoto version `0.0.25` 

---

ceph_deploy/hosts/remotes.py
ceph_deploy/rgw.py

Right now the ceph RPM package does not create /var/lib/ceph/radosgw automatically.
ceph-deploy tries to write into  /var/lib/ceph/radosgw/{cluster}-{name}, and fails to create it when /var/lib/ceph/radosgw does not exist. Switch to a os.makedirs call from a os.mkdir call so that it gets done recursively.
This will be safe to keep even if the RPM package starts create /var/lib/ceph/radosgw itself.

Create /var/lib/ceph/radosgw/{cluster}-{name} recursively

---

ceph_deploy/rgw.py
ceph_deploy/tests/test_cli_rgw.py
docs/source/changelog.rst
docs/source/rgw.rst

If a custom RGW daemon name is given, prefix it with 'rgw.'.
Update docs and help to clarify this is done.
Fixes: http://tracker.ceph.com/issues/11561

Better handling of custom RGW daemon names

---

ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/debian/install.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/hosts/rhel/install.py
ceph_deploy/hosts/suse/install.py
ceph_deploy/install.py
ceph_deploy/tests/test_install.py
ceph_deploy/util/constants.py

Only supports the package split by using the new packages for RHEL systems only *unless* specified with the new flags. No other distro is affected although the changes should allow to turn this feature "on" at a later point.
Reference ticket: http://tracker.ceph.com/issues/10894

support for package split

---

ceph_deploy/install.py
ceph_deploy/tests/test_install.py

This is a convenience option for users setting "admin" nodes.  If a user is going to run ``ceph-deploy admin`` on a node, the only package it really needs on that node to use the CLI is ``ceph-common``.  We had no way to allow a user to only install that.
This feature builds on top of the package split support, and thus this option only works on distros/versions with the package split in place.  Right now that is only downstream RHCS.
``ceph-common`` does not need to be added the default list of packages anywhere because it is always a dependency when it is needed.

Add --cli/--common option to ceph-deploy install

---

ceph_deploy/mds.py

Enable MDS services for distros using systemd.
Signed-off-by: Goldwyn Rodrigues <rgoldwyn@suse.com>

mds: enable on create with systemd

---

ceph_deploy/exc.py
ceph_deploy/new.py

We know that custom names are not supported with the sysvinit scripts, and we check for this when doing ``ceph-deploy install``, but not ``ceph-deploy new``.  This means that we happily create new Ceph config files that aren't going to be useful if any of the initial monitors use sysvinit.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1222505

Disallow custom cluster names with 'new' command and sysvinit hosts

---

ceph_deploy/hosts/suse/uninstall.py

This is because ceph-deploy tries to remove a package that does not exist.
To fix this we need to change package name to correct name ceph-radosgw
from the old name radosgw.

suse.uninstall: ceph-deploy purge fails on SUSE.

---

ceph_deploy/hosts/suse/install.py

zypper may not pull in latest packages if the repository cache is not updated
so we should do a 'zypper ref' before installing packages.

suse/install.py: SUSE zypper refresh

---

ceph_deploy/admin.py
ceph_deploy/hosts/remotes.py
ceph_deploy/tests/test_cli_admin.py

When using the ``ceph-deploy admin`` command, the client.admin key would get written with 0644 permissions, making it world readable within /etc/ceph.
This PR makes sure that it is written with 0600 permissions, and adds tests for it as well.

Fix CVE-2015-4053 world-readable permissions on client.admin key

---

ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/centos/uninstall.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/hosts/fedora/uninstall.py
ceph_deploy/hosts/rhel/uninstall.py
ceph_deploy/hosts/suse/install.py

I incorrectly thought in https://github.com/ceph/ceph-deploy/pull/282 that these changes were no longer needed.

[BZ-1221830] radosgw pkg is ceph-radosgw on RPM systems

---

ceph_deploy/conf/cephdeploy.py
ceph_deploy/tests/unit/test_conf.py
docs/source/conf.rst

Setting a default flag in `cephdeploy.conf` flag should work, except that for this specific case, where a boolean flag was needed (vs. a flag with a value) it was not getting parsed correctly.
This PR addresses this problem and documents the example that was needed for the related issue.
Reference ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1219310

allow to skip rpm imports with `cephdeploy.conf`

---

ceph_deploy/conf/cephdeploy.py
ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/debian/install.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/hosts/suse/install.py
ceph_deploy/install.py
ceph_deploy/tests/unit/util/test_paths.py
ceph_deploy/util/constants.py
ceph_deploy/util/paths/__init__.py
ceph_deploy/util/paths/gpg.py
docs/source/conf.rst
docs/source/install.rst

Grab the GPG release/autobuild key from git.ceph.com instead of ceph.com/git.
Do some cleanup to make this URL only be defined in one place.
Ref: http://tracker.ceph.com/issues/11406

Use git.ceph.com for GPG keys

---

ceph_deploy/cli.py
ceph_deploy/tests/unit/test_cli.py
ceph_deploy/tests/util.py

Example output:
(ceph-deploy)papaya-2 ~/tmp/foo ᓆ ceph-deploy new node2
[ceph_deploy.conf][DEBUG ] found configuration file at: /Users/alfredo/tmp/foo/cephdeploy.conf
[ceph_deploy.cli][INFO  ] Invoked (1.5.25): /Users/alfredo/.virtualenvs/ceph-deploy/bin/ceph-deploy new node2
[ceph_deploy.cli][INFO  ] ceph-deploy options:
[ceph_deploy.cli][INFO  ]  username                      : None
[ceph_deploy.cli][INFO  ]  func                          : <function new at 0x103e23aa0>
[ceph_deploy.cli][INFO  ]  verbose                       : True
[ceph_deploy.cli][INFO  ]  overwrite_conf                : False
[ceph_deploy.cli][INFO  ]  prog                          : ceph-deploy
[ceph_deploy.cli][INFO  ]  quiet                         : False
[ceph_deploy.cli][INFO  ]  cd_conf …

at runtime, display all flags and values

---

ceph_deploy/hosts/debian/install.py

For whatever reason, Debian Wheezy will not accept the SSL cert on git.ceph.com, though other distros seem to be fine with it.  So, switch to http for that distro.
Reference: http://tracker.ceph.com/issues/11572

[RM-11572] use http to get GPG key on Wheezy

---

ceph_deploy/calamari.py
ceph_deploy/config.py
ceph_deploy/mds.py
ceph_deploy/mon.py
ceph_deploy/osd.py
ceph_deploy/rgw.py
ceph_deploy/tests/parser/test_calamari.py
ceph_deploy/tests/parser/test_disk.py
ceph_deploy/tests/parser/test_mon.py
ceph_deploy/tests/parser/test_osd.py
ceph_deploy/util/help_formatters.py

This patchset changes the argparse config to use more subparsers to have much better help output and only list CLI options that are relevant to a given subcommand.  This may be best demonstrated by example.  Let's look at the `mon` subcommand.
`mon --help` before:
```
$ ceph-deploy mon --help
usage: ceph-deploy mon [-h] [--address [ADDRESS]] [--keyrings [KEYRINGS]]
{add,create,create-initial,destroy} [mon [mon ...]]
Subcommands:
create-initial
Will deploy for monitors defined in `mon initial members`, wait until
they form quorum and then gatherkeys, reporting the monitor status along
the process. If monitors don't form quorum the command will eventually
time out.
create
Deploy monitors by specifying them like:
ceph-deploy mon create node1 node2 node3
If no hosts are passed it will default …
```

Use argparse subparsers when subcommands have their own subcommands

---

ceph_deploy/config.py
ceph_deploy/mds.py
ceph_deploy/mon.py
ceph_deploy/rgw.py
ceph_deploy/tests/parser/test_config.py
ceph_deploy/tests/parser/test_mds.py
ceph_deploy/tests/parser/test_mon.py
ceph_deploy/tests/parser/test_rgw.py

When we require one or more hosts on the CLI, use `nargs='+'`.
For `mon add` we only allow 1 host, so use `nargs=1`.  This preserves the existing behavior of having the hostnames be in a list.
Remove code that checked for this after argument parsing, leave the enforcement to argparse itself (which is now validated through our unit tests).
http://tracker.ceph.com/issues/12150

Enforce proper number of hosts on CLI

---

ceph_deploy/pkg.py
ceph_deploy/tests/parser/test_pkg.py

http://tracker.ceph.com/issues/12171
The code could not handle both `--install` and `--remove` being present, so make sure that we
don't allow that on the CLI.
Add unit tests for pkg.
Remove `nargs='?'`. Using '?' doesn't make any sense unless a `default`
or `const` flag is also provided, which they aren't.  We want to make
sure there is one string provided, which is the default behavior.

[RM-12171] Make pkg --install and --remove mutually exclusive

---

ceph_deploy/osd.py
ceph_deploy/tests/parser/test_disk.py
ceph_deploy/tests/parser/test_osd.py

http://tracker.ceph.com/issues/12168
Not sure why this was ever seen as necessary.  With the store_true
action, it will be False if not present, True if passed on the CLI.
We just need to the boolean value, and there is no need to set
the flag to None instead of False when it is not present.

[RM-12168] Don't use store_true and default=None

---

ceph_deploy/hosts/suse/install.py
ceph_deploy/hosts/suse/uninstall.py
ceph_deploy/tests/unit/hosts/test_suse.py
ceph_deploy/util/pkg_managers.py

As raised:
http://article.gmane.org/gmane.comp.file-systems.ceph.devel/25511
This change set implements option (2), where install() triggers the installation of packages from existing (distribution) repositories.
Component based installation is also fixed, through the use of a component->package name mapping function.
Changes since v2 (#312):
- Remove unused imports (Thanks Travis)
- Rebase against latest upstream
Changes since v1 (#308):
- Test ceph-deploy component -> SUSE package name mapping (Thanks Ken)
- Rebase against latest upstream

Fix package installation on SUSE platforms v3

---

ceph_deploy/hosts/common.py
ceph_deploy/hosts/remotes.py
ceph_deploy/tests/test_cli_admin.py

If Ceph is running under separate ceph user, it requires access
to various files under this user.
This patch tries to set owner of these files to the current owner
of base_dir (/var/lib/ceph).
If the ceph directory is owned by root, it expects old installation
and should work with old tools as well (avoids --setuser option).
Signed-off-by: Milan Broz <mbroz@redhat.com>

Set owner of directory and keyrings according to owner of /var/lib/ceph.

---

ceph_deploy/rgw.py

https://bugzilla.redhat.com/show_bug.cgi?id=1228842
Let the user know the default port has been used for RGW, as the
default port is probably not one people will guess.
We just hardcode the port number for now, since ceph-deploy doesn't allow the user to change the port number when deploying RGW.

[BZ-1228842] Echo RGW default port during rgw create

---

ceph_deploy/mon.py

http://tracker.ceph.com/issues/12374
When using mon_create_initial(), we already have list of initial mon
members from the config file.  Pass it to mon_create() in args.mon
so that mon_create() does not throw an exception when it finds that
args.mon does not exist.
This is actually an optimization as well. mon_create_initial() always
looked up mon_initial_members from the config file, but didn't pass that
to mon_create().  mon_create() would then see that args.mon was empty
and then look up mon_initial_members *again*.  Now we only need to open
and read the file once.
Fixes: #12374

[RM-12374] Pass mon host list from ceph.conf to mon_create

---

ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/centos/uninstall.py
ceph_deploy/hosts/debian/uninstall.py
ceph_deploy/hosts/fedora/__init__.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/hosts/fedora/uninstall.py
ceph_deploy/hosts/rhel/uninstall.py
ceph_deploy/hosts/suse/uninstall.py
ceph_deploy/install.py
ceph_deploy/util/pkg_managers.py

This PR does two things:
(1) uses DNF as the package manager for Fedora >= 22
(2) Introduces Yum and DNF package manager classes
The new package manager classes can be instantiated at the time of a call to hosts.get(), with the module only needing to decide once which manager is the correct one.  I've only added this to Fedora right now, as an early adopter of the new code.
I would like to use this everywhere, and think it makes the code a lot cleaner.
Specifically for this change, Fedora installs are a bit weird because F22 packages are only available from the gitbuilders, so you have to do "ceph-deploy install --dev master <HOST>" to try it out.  Becuase it's a dev install, it actually uses centos.mirror_install() :disappointed: to write out a .repo file, so you will still see some …

Class-based package managers to add DNF support for Fedora 22

---

ceph_deploy/admin.py
ceph_deploy/cli.py
ceph_deploy/install.py
ceph_deploy/mon.py
ceph_deploy/new.py

Most of what I had intended to under http://tracker.ceph.com/issues/12083 got split out into different issues and have already been resolved (Yay!).
This is just a couple of minor things that I had queued up that didn't go in yet.
The `prog` variable in the argparse namespace always confused me.  It's called out as an "ugly kludge", but it's not actually used anywhere.  Kill it!

More help/argparse cleanup

---

ceph_deploy/hosts/debian/install.py

See: http://tracker.ceph.com/issues/12541
gdisk has been a proper dependency in Ceph packages since before
Firefly.  There is no need to install it directly.
Fixes: #12541

Drop explicit gdisk in debian/install

---

ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/common.py
ceph_deploy/hosts/debian/install.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/hosts/suse/install.py
ceph_deploy/tests/unit/hosts/test_common.py
ceph_deploy/tests/unit/hosts/test_suse.py

http://tracker.ceph.com/issues/12543
This PR makes it such that `install --rgw` only installs radosgw, `--cli` only installs ceph-common, etc.
This does preserve backwards-compatibility. The default is still "everything", where everything is MON, OSD, MDS, and RGW.  This just makes it such that if a user requests specific daemons, we install the minimal set of packages that can satisfy the request.
That set of packages can be different depending on OS.  For example, debian packages have a separate `ceph-mds` package (enabling it to be installed by itself), but EL/RPM packages do not.
I tested that this didn't break anything by running this sequence of commands on Trusty, CentOS 7, and Fedora 22:
```
ceph-deploy install --cli <node>
ceph-deploy install --rgw <node>
ceph-deploy install …
```

Only install requested packages for Debian, CentOS, Fedora

---

ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/centos/__init__.py
ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/centos/uninstall.py
ceph_deploy/hosts/debian/__init__.py
ceph_deploy/hosts/debian/install.py
ceph_deploy/hosts/debian/uninstall.py
ceph_deploy/hosts/rhel/__init__.py
ceph_deploy/hosts/rhel/install.py
ceph_deploy/hosts/rhel/uninstall.py
ceph_deploy/hosts/suse/__init__.py
ceph_deploy/hosts/suse/install.py
ceph_deploy/hosts/suse/uninstall.py
ceph_deploy/util/pkg_managers.py

First added for Fedora/DNF, move all the other install/uninstall tasks to using the pkg manager classes.
There is still more work to do on top of this, but this is a big start.
Tested install/uninstall on CentOS 7, Trusty, and RHEL 7 and had no problems here.
http://tracker.ceph.com/issues/12439

Use package manager classes for remaining distros

---

ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/debian/install.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/hosts/remotes.py
ceph_deploy/hosts/rhel/install.py
ceph_deploy/repo.py
ceph_deploy/tests/parser/test_repo.py
ceph_deploy/util/pkg_managers.py
ceph_deploy/util/templates.py
setup.py

This introduces a new `ceph-deploy repo` set of commands.
You can use `ceph-deploy repo` to create or delete repo files by name.  The repo details can be passed in my `--gpg-url` and `--repo-url`.  Note that for RPM systems, this command only supports the basic "ceph" template -- meaning that it will always put three entries into a single `.repo` file for [ceph], [ceph-noarch], and [ceph-source].
We could potentially swap this out for the more flexible custom/arbitrary repo definitions if that is deemed worthwhile.  Even if we think that it might be, let's talk about it because I don't want to **not** be able to switch to it later for backwards compatibility reasons because we didn't start that way.
I haven't tested yet that this works when reading repos from `cephdeploy.conf`.  I need to …

Add "ceph-deploy repo" command

---

ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/util/pkg_managers.py

Since DNF natively supports priorities, just skip all the priorities stuff if we're not Yum.
Skip the check_obsoletes on DNF as well.
I didn't like having a "install_specific_package...()" method in the package manager classes, so I created a helper to return the name and just used the regular install() method instead.
Tested on CentOS and Fedora.  Seems to work!
http://tracker.ceph.com/issues/12477

Only install priorities plugin when using Yum

---

ceph_deploy/hosts/debian/install.py
ceph_deploy/hosts/debian/uninstall.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/util/pkg_managers.py

Doing `dnf install pkg` does not actually upgrade the package if it is already installed.  But adding `--best` will make it do so.
There are more commits here than necessary to just add `--test` to the DNF call.  The other commits are to modify the install() and remove() methods of the package manager classes to take `**kw`, and to pass keyword args for adding extra flags to install and remove calls.
The individual commits make sense.
http://tracker.ceph.com/issues/12480

Allow package upgrades with DNF

---

tox.ini

Reference issue: http://tracker.ceph.com/issues/12631

[RM-12631] catch syntax errors in tox runs

---

ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/centos/__init__.py
ceph_deploy/hosts/debian/__init__.py
ceph_deploy/hosts/fedora/__init__.py
ceph_deploy/hosts/rhel/__init__.py
ceph_deploy/hosts/suse/__init__.py
ceph_deploy/osd.py
ceph_deploy/tests/unit/hosts/test_suse.py

Once systemd integration is ready, "systemctl enable ceph" fails
because there is no longer such service (OSD units are generated).
Signed-off-by: Milan Broz <mbroz@redhat.com>
Also see https://github.com/ceph/ceph-deploy/commit/8360fb501aa8a3b8dc20423c1575379b3d30690e

Do not enable non-existing ceph service on systemd managed EL distros.

---

ceph_deploy/util/pkg_managers.py

for EL6 compatibility
http://tracker.ceph.com/issues/12663

use 'rpm --import', not 'rpmkeys --import'

---

ceph_deploy/hosts/centos/__init__.py
ceph_deploy/hosts/centos/mon/create.py
ceph_deploy/hosts/fedora/__init__.py
ceph_deploy/hosts/fedora/mon/create.py
ceph_deploy/hosts/rhel/__init__.py
ceph_deploy/hosts/rhel/mon/create.py

To properly install systemd-enabled and old (sysvinit) Ceph packages
we need to properly detect when systemd target is used.
This cannot be done just by checking distro version, it depends
on Ceph package content (sysvinit can be used on systemd distro as well).
Let's check ceph.target existence and enable systemd only in this case.
Signed-off-by: Milan Broz <mbroz@redhat.com>

Detect and support both systemd and sysvinit on Fedora, RHEL and CentOS

---

ceph_deploy/hosts/common.py

http://tracker.ceph.com/issues/12649
When going from 1 monitor to 2 (via ceph-deploy mon add), there is
a problem such that the existing monitor cannot reach quorum
once you "ceph mon add", because 2 mons require conensus.  But the
2nd monitor isn't running yet, so they are stuck.
As it turns out, calling `ceph mon add` is completely unnecessary, so just remove it entirely.
Via manual testing, I was able to move from 1-->2 mons, then 2-->3 mons without any problems with this change.
Fixes: #12649

mon add: start new mon without calling 'ceph mon add'

---

ceph_deploy/hosts/__init__.py
ceph_deploy/mon.py
ceph_deploy/osd.py
ceph_deploy/tests/unit/util/test_packages.py
ceph_deploy/util/packages.py
ceph_deploy/util/versions.py

This is a PR with a bit of feature creep: the intent was to use the new `Ceph` object to provide an interface for versions and use it to map it against supported `systemd` versions.
It is not entirely sure if this approach will be used, but for now this can be used to fix (http://tracker.ceph.com/issues/11115) which allows to check if Ceph is installed and error accordingly. 
The "check if ceph is installed" comes free with this implementation, if we decide later to not use versions we can change the approach.
This PR also moves the private function in `hosts/__init__.py` to `util.versions` because the functionality is now being used by more than one place. At some point the tests should map to the new location - but all tests pass as it is now.

check if ceph is installed

---

ceph_deploy/mon.py

Originally reported by @blubanovic-penguin
the call to `get_connection()` was broken because of being passed a `callbacks` arg, which it didn't accept.
The way that callbacks were implemented in `hosts.get()` mandate that the callbacks be passed a `module` argument -- that module is the one returned (and determined by) `hosts.get()`.  This means that `get_connection` cannot be extended to take the same callbacks as `hosts.get()`.
But this is okay, because there doesn't seem to be a good reason for this function to use `get_connection`.  @alfredodeza mentioned in #346 that it used different defaults than `hosts.get()`, but looking at the source I don't see that being the case.
http://tracker.ceph.com/issues/12699

use hosts.get() instead of get_connection for mon create-initial

---

ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/debian/install.py
ceph_deploy/hosts/fedora/install.py
ceph_deploy/install.py

Adjusted centos, debian, fedora.
suse and rhel don't seem to pay attention to version_kind... :/

install: add support for --dev-commit <sha1>

---

ceph_deploy/install.py
ceph_deploy/tests/test_install.py

We need this for the teuthology tests.
Don't include it in --all, since any normal person does not want it.

install: add --test install option to install ceph-test package

---

ceph_deploy/forgetkeys.py

[RM-12999] remove bootstrap-rgw key via forgetkeys

---

ceph_deploy/tests/unit/test_mon.py

py.test 2.8.0 had a backwards incompatible change, this fixes that issue.
Reference issue http://tracker.ceph.com/issues/13230

[RM-13230] fix broken unit test, py.test issue

---

ceph_deploy/install.py

Before this patch functions "uninstall" and "purge" are almost identical.
Since the only difference is the logging messages, and when the
distro.uninstall() function is called a boolean parameter set both these
functions are merged into a single command "remove" with the parameter
purge.

install: functions "uninstall" and "purge" merged to function "remove"

---

ceph_deploy/osd.py

There is no need for osd create to call udevadm trigger action=add. By
running all actions associated with add for all block devices, it may
also trigger some race conditions. For instance, the following happens
about 10% of the time, when using dmcrypt:
* ceph-disk prepare --dmcrypt /dev/vdb
* /dev/vdb1 starts activating via udev
* ceph-deploy triggers action=add
* /dev/vdb2 udev chown root /dev/vdb2
* /dev/vdb1 activate fails because of permission denied on /dev/vdb2
* /dev/vdb2 udev action chown ceph /dev/vdb2
http://tracker.ceph.com/issues/13299 Fixes: #13299
Signed-off-by: Loic Dachary <loic@dachary.org>

do not udevadm trigger, ceph-disk does it

---

ceph_deploy/cli.py
ceph_deploy/util/log.py

An Example of the output here:
```
ceph-deploy gatherkeys mon1
[2015-11-23 11:55:09.049981][ceph_deploy.conf][DEBUG ] found configuration file at: /home/vagrant/.cephdeploy.conf
[2015-11-23 11:55:09.050858][ceph_deploy.cli][INFO  ] Invoked (1.5.28): /home/vagrant/bin/ceph-deploy gatherkeys mon1
[2015-11-23 11:55:09.051282][ceph_deploy.cli][INFO  ] ceph-deploy options:
[2015-11-23 11:55:09.051730][ceph_deploy.cli][INFO  ]  username                      : None
[2015-11-23 11:55:09.052110][ceph_deploy.cli][INFO  ]  verbose                       : False
```
I'm happy to discuss my proposed solution. 
For tracker see: http://tracker.ceph.com/issues/13585

[RM-13585] Add timestamp to console and log output

---

ceph_deploy/mon.py

Issue tracker http://tracker.ceph.com/issues/14049
Successful output looks like this for a systemd box:
...
[ceph_deploy.mon][DEBUG ] Removing mon from node4
[node4][DEBUG ] connection detected need for sudo
[node4][DEBUG ] connected to host: node4
[node4][DEBUG ] detect platform information from remote host
[node4][DEBUG ] detect machine type
[node4][DEBUG ] find the location of an executable
[node4][DEBUG ] get remote short hostname
[node4][INFO  ] polling the daemon to verify it stopped
[node4][INFO  ] Running command: sudo service ceph status mon.node4
[node4][INFO  ] Running command: sudo mkdir -p /var/lib/ceph/mon-removed
[node4][DEBUG ] move old monitor data

[RM-14049] deal with systemd when stopping a mon otherwise raise an error

---

setup.py

fixes http://tracker.ceph.com/issues/13909
With the following commit:
https://github.com/alfredodeza/remoto/commit/f9c8e87a8e3fc48bd122c86953ec87ac1be13a10
remoto 0.0.26 is now released
/cc @ktdreyer

[RM-13909] bump requirement for remoto

---

setup.py

fixes http://tracker.ceph.com/issues/14156 with remoto's commit:
https://github.com/alfredodeza/remoto/commit/1aab2445bd8ec094c2bf8875c012415877b23a6c

[14156] bump remoto to 0.0.27

---

ceph_deploy/new.py
ceph_deploy/tests/test_cli_new.py

This patch removes option "filestore_xattr_use_omap"
from default ceph.conf global section,
as this option was removed in #7408.
Cleanup #14355
Signed-off-by: Vikhyat Umrao <vumrao@redhat.com>

[RM-14355] Remove "filestore xattr use omap = true"

---

ceph_deploy/hosts/debian/__init__.py
ceph_deploy/mon.py
ceph_deploy/tests/unit/util/test_system.py
ceph_deploy/util/system.py

So that we are able to fallback sensibly to detect upstart and make it easier on systems where monitors weren't added by ceph-deploy.
https://bugzilla.redhat.com/show_bug.cgi?id=1282484

Init fallback for upstart

---

ceph_deploy/pkg.py

Do not timeout too early, here. If we use the pkg command to install
e.g. ceph-selinux or some other package with long post script we can
easily timeout in 5 minutes, disabling the timeout completely for the
pkg install procedure makes this much more safe.
The same holds for pkg removal.
Signed-off-by: Boris Ranto <branto@redhat.com>

ceph-deploy: Disable timeout for pkg install/remove procedures

---

ceph_deploy/osd.py

Refactored out some direct executable calls in "osd.py". 
Should we do that for all executable calls in ceph-deploy?
For tracker see: http://tracker.ceph.com/issues/13847

[RM-13847] Using full paths to executables

---

ceph_deploy/osd.py

This will pass --bluestore on to ceph-disk during the prepare/create
step.
Tested on my local jessie box.  Works, except that ceph-detect-init is wrong,
but that's a different issue.

osd,disk: add --bluestore flag

---

ceph_deploy/cli.py

This patch renames ceph-deploy log file to ceph-deploy-${CLUSTER}.log
Fixes: #15112
Signed-off-by: Vikhyat Umrao <vumrao@redhat.com>

[RM-15112] Rename ceph-deploy log file to ceph-deploy-${CLUSTER}.log

---

ceph_deploy/osd.py

http://tracker.ceph.com/issues/15409
Change the function name "create_osd" to "create_osd_keyring".
This function just do:
1. Check the remote node's osd keyring exist or not
2. If not, it create one.
The original name would confused the developers.
Signed-off-by: DesmondS <jordanjimmy41177@gmail.com>

Fix the function name of osd keyring creation

---

ceph_deploy/gatherkeys.py
ceph_deploy/tests/test_gather_keys.py
ceph_deploy/tests/test_gather_keys_missing.py
ceph_deploy/tests/test_gather_keys_with_mon.py
ceph_deploy/tests/test_keys_equivalent.py
docs/source/admin.rst
docs/source/gatherkeys.rst
docs/source/index.rst
docs/source/mon.rst

Use the mon keyring to gather keys directly from the mon.
This is better than relying on:
ceph-create-keys --cluster ${cluster_name} --id ${mon_id}
Which is started as a side effect of booting a mon. This side effect has
numerous issues as stated in this thread on ceph-devel:
http://comments.gmane.org/gmane.comp.file-systems.ceph.devel/30552
The conclusion is that ceph will remove this side effect, after ceph-deploy
has a fix. This fix removes that dependency.

[RM-15451] Gather keys directly from the mon

---

ceph_deploy/install.py

We should use the configured username for rsync to connect
to the remote host.
Signed-off-by: Wanlong Gao <wanlong.gao@easystack.cn>

Fix rsync username when using local_mirror

---

ceph_deploy/hosts/debian/install.py

ceph is now split into ceph-mon and ceph-osd, this might actually break hammer installs if the packages are not split there, needs some good testing.

Handle ubuntu package split for ceph-osd and ceph-mon

---

ceph_deploy/hosts/centos/__init__.py

If ceph packages aren't installed on the host with systemd preinstalled, script will return sysvinit instead of systemd which is invalid.

modify sysvinit if condition

---

ceph_deploy/hosts/common.py

When running ceph-deploy --cluster <name> mon add <host> failure occurs due to the following two commands being run by ceph-deploy without the --cluster <name> arg:
ceph mon getmap -o /var/lib/ceph/tmp/vpm1.vpm1-osd1.monmap
ceph-mon -i vpm1-osd1 --pid-file /var/run/ceph/mon.vpm1-osd1.pid --public-addr 192.168.99.49
This breaks ceph-deploy's ability to add monitors to a non-default named cluster.
More info at http://tracker.ceph.com/issues/17238
This commit adds the two arg lines to fix this.
I apologise if I haven't follow the correct procedure with this, it's my first contribution to Ceph.

Add --cluster arg as required to two commands

---

ceph_deploy/hosts/debian/install.py

In a test deployment, hosting ceph packages in a local mirror and
installing them across the cluster will be ideal. Current ceph-deploy
allows unauthenticated packages when install is used but not from a
mirror location. This change helps address that usecase.
Signed-off-by: Ganesh Mahalingam <ganesh.mahalingam@intel.com>

Allow unsigned deb packages install from mirror locations

---

ceph_deploy/hosts/debian/install.py

If ceph-ceph_deploy is called with:
'install node1 --no-adjust-repos --nogpgcheck'
python trace shows this error:
UnboundLocalError: local variable 'extra_install_flags'
referenced before assignment
Signed-off-by: Danny Al-Gaaf <danny.al-gaaf@bisect.de>

fix UnboundLocalError

---

ceph_deploy/hosts/centos/__init__.py

Reference isssue: http://tracker.ceph.com/issues/17287

[RM-17287] hosts: detect systemd before sysvinit in centos

---

ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/centos/install.py
ceph_deploy/hosts/remotes.py
ceph_deploy/tests/unit/hosts/test_hosts.py

Virtuozzo Linux based on CentOS and got the same major release number and empty codename.
import platform
platform.linux_distribution()
('Virtuozzo Linux', '7.3', '')

[RM-19301] add Virtuozzo Linux support

---

ceph_deploy/mgr.py

This is to enable mgr daemons to remote control
mds and osd daemons using MCommand messages.
Fixes: http://tracker.ceph.com/issues/19713
Signed-off-by: John Spray <john.spray@redhat.com>

mgr: update osd and mds caps

---

ceph_deploy/tests/test_install.py

Maybe someone forgets to fix test info in test_install.py.
E AssertionError: assert ['ceph', 'cep...d', 'radosgw'] ==
['ceph-mds', '...d', 'radosgw']
E   At index 0 diff: 'ceph' != 'ceph-mds'
E   Full diff:
E   - ['ceph', 'ceph-mds', 'ceph-mon', 'ceph-osd', 'radosgw']
E   ?  --------
E   + ['ceph-mds', 'ceph-mgr', 'ceph-mon', 'ceph-osd', 'radosgw']
E   ?              ++++++++++++
So fix it.
Signed-off-by: Yu Shengzuo <yu.shengzuo@99cloud.net>

Test: Fix some contrast infomation in test case

---

ceph_deploy/cli.py
ceph_deploy/tests/parser/test_main.py

It still uses 'ceph' everywhere but disables this customization 
http://tracker.ceph.com/issues/20228

remove custom cluster names for deploying

---

ceph_deploy/osd.py

ceph-disk now defaults to bluestore, which means there wasn't a way to
provision filestore.

osd: add --filestore

---

ceph-deploy.spec

This patch is straight from http://tracker.ceph.com/issues/16399, seems like its hit with openstack mitaka repo.
python-distribute was merged back into python-setuptools, so there should be no reason to require both.

remove python-distribute dependency

---

ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/remotes.py
ceph_deploy/tests/test_remotes.py

On systems with only /etc/os-release (rather than distro-specific
release files), platform.linux_distribution() returns ('', '', '').
In this case, fall back to a trivial parsing of /etc/os-release.
It would be cleaner to use the new distro.linux_distribution()
function, especially since platform.linux_distribution() is
deprecated, but I don't know that there's a way of ensuring that
module is present in advance on all the remote hosts.
Fixes: http://tracker.ceph.com/issues/18164
Signed-off-by: Tim Serong <tserong@suse.com>

Use /etc/os-release if platform.linux_distribution() empty

---

ceph_deploy/mgr.py

If `/var/lib/ceph/mgr` directory is missing, `safe_mkdir` still does not fail, but subsequent code is unable to reach `/var/lib/ceph/mgr/cluster-hostname` directory, which will not be created (as `mgr` folder is missing)
This is formatted under contribution guidelines, as noted in #458.
Link to redmine issue: [22712](http://tracker.ceph.com/issues/22712)

[RM-22712] Use recursive dir creation

---

bootstrap
ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/arch/__init__.py
ceph_deploy/hosts/arch/install.py
ceph_deploy/hosts/arch/mon/__init__.py
ceph_deploy/hosts/arch/uninstall.py
ceph_deploy/install.py
ceph_deploy/tests/test_install.py
ceph_deploy/tests/unit/hosts/test_hosts.py
ceph_deploy/util/constants.py
ceph_deploy/util/pkg_managers.py
ceph_deploy/util/system.py
docs/source/install.rst

With the help of a friend, we added support for Arch Linux.
We tested it several times on different machines and VMs to make sure it works as expected.
I was specially careful on not changing current functionality.

RM-7505 Add support for Arch Linux

---

ceph_deploy/osd.py

Fixes https://tracker.ceph.com/issues/22816
Before:
(ceph-deploy) papaya-2 ~/tmp/foo ᓆ ceph-deploy disk list node8
[ceph_deploy.conf][DEBUG ] found configuration file at: /Users/alfredo/tmp/foo/cephdeploy.conf
[ceph_deploy.cli][INFO  ] Invoked (2.0.0): /Users/alfredo/.virtualenvs/ceph-deploy/bin/ceph-deploy disk list node8
[ceph_deploy.cli][INFO  ] ceph-deploy options:
[ceph_deploy.cli][INFO  ]  username                      : None
[ceph_deploy.cli][INFO  ]  verbose                       : False
[ceph_deploy.cli][INFO  ]  debug                         : False
[ceph_deploy.cli][INFO  ]  overwrite_conf                : False
[ceph_deploy.cli][INFO  ]  subcommand                    : list
[ceph_deploy.cli][INFO  ]  quiet                         : False
[ceph_deploy.cli][INFO  ]  cd_conf …

[RM-22816] osd use logger.info to get the output on disk list

---

ceph_deploy/mds.py
ceph_deploy/mgr.py

If we fail to get hostname, the hosts.get will raise an exception and
don't return any value, so the variable distro in [1] and [2] may be
undefined. What's worse, we may get previous value if we fail in second
time but succeed in first time.
In order to avoid the issues above, we should initialize the distro
value in each loop iteration.
[1] https://github.com/ceph/ceph-deploy/blob/master/ceph_deploy/mgr.py#L173
[2] https://github.com/ceph/ceph-deploy/blob/master/ceph_deploy/mds.py#L173

[RM-23218] fix UnboundLocalError when create mds/mgr with bad hosts

---

ceph-deploy.spec
debian/control
setup.py

A change in the remoto version caused vendoring not to work anymore. We now declare our dependencies directly in Python, spec file, and control file.
Bumps remoto to use the latest version available (0.0.35 at this time) which fixes the following error:
NameError: global name 'extend_path' is not defined
Fixes: http://tracker.ceph.com/issues/37848

Fix remoto vendoring, bump remoto version to 0.0.35

---

ceph_deploy/tests/conftest.py
ceph_deploy/tests/test_cli_new.py

Caused by new pytest version.
Fixes: http://tracker.ceph.com/issues/37939

Fix hard deprecation errors in tests

---

ceph_deploy/tests/unit/hosts/test_altlinux.py

The commit 6190bb2 introduced an unnecessary print statement in the
altlinux tests.
Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

test_altlinux: Remove print statement

---

ceph_deploy/hosts/__init__.py

My server has installed Huawei EulerOS(v2.0sp8-arm64 Kunpeng920) and it's a client server in my ceph cluster. url:https://developer.huaweicloud.com/en-us/euleros/download.html?developlan=Other
[root@client12 ~]# cat /etc/os-release
NAME="EulerOS" 
VERSION="2.0 (SP5)" 
ID="euleros" 
ID_LIKE="rhel fedora centos" 
VERSION_ID="2.0" 
PRETTY_NAME="EulerOS 2.0 (SP5)" 
ANSI_COLOR="0;31"
When I use ceph-deploy commond to push ceph conf file to this client, I get following error:
root@node1:/etc/ceph# ceph-deploy --overwrite-conf config push client12
[ceph_deploy.conf][DEBUG ] found configuration file at: /root/.cephdeploy.conf
[ceph_deploy.cli][INFO ] Invoked (2.0.1): /usr/bin/ceph-deploy --overwrite-conf config push client12
[ceph_deploy.cli][INFO ] ceph-deploy options:
[ceph_deploy.cli][INFO ] …

Add support for EulerOS

---

ceph_deploy/hosts/remotes.py

The deprecated platform.linux_distribution function was removed
in Python 3.8 - fallback to using parse_os_release if the function
is not found.
Signed-off-by: James Page <james.page@ubuntu.com>

Fix compatibility with Python 3.8

---

ceph_deploy/hosts/__init__.py
ceph_deploy/tests/unit/hosts/test_hosts.py

os_path http://117.78.1.88:82/dailybuilds/openeuler/mainline/openEuler-20.03-LTS/
my test environment is Kunpeng 920s
[root@openeuler ~]# cat /etc/os-release 
NAME="openEuler"
VERSION="20.03 (LTS)"
ID="openEuler"
VERSION_ID="20.03"
PRETTY_NAME="openEuler 20.03 (LTS)"
ANSI_COLOR="0;31"
[root@openeuler ~]# ceph-deploy new openeuler
[ceph_deploy.conf][DEBUG ] found configuration file at: /root/.cephdeploy.conf
[ceph_deploy.cli][INFO  ] Invoked (2.0.1): /usr/bin/ceph-deploy new openeuler
[ceph_deploy.cli][INFO  ] ceph-deploy options:
[ceph_deploy.cli][INFO  ]  username                      : None
[ceph_deploy.cli][INFO  ]  verbose                       : False
[ceph_deploy.cli][INFO  ]  overwrite_conf                : False
[ceph_deploy.cli][INFO  ]  quiet                         : False …

add support for openeuler

---

ceph_deploy/hosts/__init__.py

I want to deploy or manage ceph via ceph-deploy on Kylin OS.
1. Unsupported OS reported during execution:
```
root@slave1:/tmp# ceph-deploy uninstall slave1
[ceph_deploy.conf][DEBUG ] found configuration file at: /root/.cephdeploy.conf
[ceph_deploy.cli][INFO  ] Invoked (2.0.1): /usr/bin/ceph-deploy uninstall slave1
[ceph_deploy.cli][INFO  ] ceph-deploy options:
[ceph_deploy.cli][INFO  ]  username                      : None
[ceph_deploy.cli][INFO  ]  verbose                       : False
[ceph_deploy.cli][INFO  ]  overwrite_conf                : False
[ceph_deploy.cli][INFO  ]  quiet                         : False
[ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x7f91c9e170>
[ceph_deploy.cli][INFO  ]  cluster …
```

Support kylin os to deploy ceph cluster through ceph-deploy

---

ceph_deploy/osd.py

fixed error of decode string in disk_list function of osd.
` TypeError: startswith first arg must be bytes or a tuple of bytes, not str`
this patch solved this problem which happened in python3.(compatible with python2.7)

decode string of disk list fixed

---

ceph_deploy/hosts/__init__.py
ceph_deploy/hosts/clear/__init__.py
ceph_deploy/hosts/clear/install.py
ceph_deploy/hosts/clear/mon/__init__.py
ceph_deploy/hosts/clear/uninstall.py
ceph_deploy/hosts/remotes.py
ceph_deploy/util/pkg_managers.py

This PR enables ClearLinux as a supported distribution with ceph-deploy. ClearLinux primarily only contains python3 which prompted another commit to add python3 support.

Enable ClearLinux as a supported distro

---

debian/control

subvar "${python3:Depends}" is able to fill it with the proper deps.
after this change, the depends looks like:
dpkg -I ../ceph-deploy_2.0.1_all.deb | grep Depends
Depends: python2:any, python3-remoto, python3:any
as in python3, none of
python3-argparse
python3-configparser
python3-setuptools
is needed at runtime.
Signed-off-by: Kefu Chai <kchai@redhat.com>

debian: drop unnecessary Depends
