ceph/ceph-deploy

- ceph_deploy/gatherkeys.py
- ceph_deploy/rgw.py
- setup.py
This is still mostly untested, but wanted to get up for review so it can be poked and get tested early enough to prepare for hammer release.
This is to add "ceph-deploy rgw create..." commands.
> [DNM] Deploy RGW

- ceph_deploy/install.py
> change default release to Hammer

- ceph_deploy/gatherkeys.py
- ceph_deploy/new.py
Since we couldn't cherry-pick nicely from 3cdc6cb5 due to multiple commits, this PR addresses them separately
> fix world readable keyrings

- ceph_deploy/rgw.py
- ceph_deploy/util/system.py
We were calling the wrong service name, and passing daemon names that aren't necessary.
> RGW service fixes for RPM systems

- ceph_deploy/calamari.py
Removes all the dependency on custom repos and relies on previously setup repositories.
Reference ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1219344
> fix `calamari connect`

- ceph_deploy/mds.py
- docs/source/changelog.rst
And display nicely if that is the case
Reference issue: https://bugzilla.redhat.com/show_bug.cgi?id=1218962
> don't attempt to install mds in RHEL

- ceph_deploy/hosts/__init__.py
- ceph_deploy/tests/unit/hosts/test_hosts.py
Signed-off-by: Hong Zhiguo <zhiguohong@tencent.com>
> support for distro Mint which is based on ubuntu

- ceph_deploy/mon.py
- docs/source/mon.rst
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> [BZ-1231203] throws if multiple mon are passed to "mon add"

- ceph_deploy/tests/test_cli.py
- ceph_deploy/tests/test_cli_mon.py
- ceph_deploy/tests/test_cli_new.py
- ceph_deploy/tests/test_cli_osd.py
- ceph_deploy/tests/test_cli_rgw.py
First round of cleanup for tests that I've wanted to do.  Mostly just cleaning up some imports, and renaming some tests to reflect what they actually do.
Added a few new ones for consistency between the CLI commands.
Want to see this run through Tox to see that py26 is okay with my changes.
> Some test cleanup

- ceph_deploy/install.py
- ceph_deploy/tests/parser/test_install.py
http://tracker.ceph.com/issues/12147
A bunch of things were mutually exlusive when they weren't supposed to be, and somethings weren't that should be.
> Fix mutex groups in ceph-deploy install

- tox.ini
> [RM-12330] Pin mock version to work on Python 2.6

- ceph_deploy/osd.py
> osd: enable ceph on osd create

- ceph_deploy/hosts/centos/install.py
- ceph_deploy/hosts/debian/install.py
- ceph_deploy/hosts/fedora/install.py
Ceph.com does redirects, but this is faster.
> install: go direct to download.ceph.com

- vendor.py
> vendor from git.ceph.com

- ceph_deploy/conf/cephdeploy.py
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>
> cephdeploy.conf: use more meaningful example apt repo url

- ceph_deploy/conf/cephdeploy.py
- ceph_deploy/hosts/debian/install.py
- ceph_deploy/tests/unit/util/test_paths.py
- ceph_deploy/util/constants.py
- docs/source/conf.rst
- docs/source/install.rst
- docs/source/repo.rst
This should be more reliable than the Gitweb interface.
> download GPG keys from download.ceph.com

- CONTRIBUTING.rst
> [RM-13846] create a contributing guidelines file

- debian/rules
> [RM-13934] remove no longer supported @ char from debian/rules

- docs/source/index.rst
Signed-off-by: Dan Mick <dan.mick@redhat.com>
> Typo in name of index file

- docs/source/index.rst
Signed-off-by: Dan Mick <dan.mick@redhat.com>
> Sigh, fix underline length as well

- ceph_deploy/hosts/debian/__init__.py
Fixes http://tracker.ceph.com/issues/14646
> [RM-14646] check for upstart before checking for systemd

- ceph_deploy/tests/test_cli_mon.py
Details at http://tracker.ceph.com/issues/15018
@alfredodeza says
> I am inclined to say this test is not very good and should be removed
But then I realized that the `new` call is actually tested properly, and it seems worth keeping.
> [RM-15018] Remove broken 'mon create' unittest

- setup.py
> [RM-15865] bump the remoto requirement to 0.0.28

- ceph_deploy/hosts/suse/__init__.py
- ceph_deploy/hosts/suse/mon/create.py
- ceph_deploy/tests/unit/hosts/test_suse.py
At the moment when testing with:
https://build.opensuse.org/package/show/filesystems:ceph:jewel/ceph
mon create fails, these 2 patches fix this issue.
> Fix mon install suse

- ceph_deploy/osd.py
- ceph_deploy/tests/parser/test_disk.py
- ceph_deploy/tests/parser/test_osd.py
see http://tracker.ceph.com/issues/16140
> remove the ability to use ext4 in ceph-deploy

- docs/source/contents.rst
> [RM-16452] docs: include admin.rst in the toctree

- docs/source/contents.rst
> [RM-16452] docs: include gatherkeys.rst in the toctree as well

- ceph_deploy/install.py
Fixes http://tracker.ceph.com/issues/16533
This would avoid pull request #408
> [RM-16533] install: define gpgcheck always

- ceph_deploy/tests/unit/util/test_pkg_managers.py
- ceph_deploy/util/pkg_managers.py
Please see bug http://tracker.ceph.com/issues/16979 for details of this bug.
> RM-16979 zypper fix for remove

- ceph_deploy/admin.py
- ceph_deploy/hosts/common.py
- ceph_deploy/mds.py
- ceph_deploy/rgw.py
Signed-off-by: MinSheng Lin <minsheng.l@inwinstack.com>
> [RM-17053] cleanup: using load_raw to replace old practice

- ceph_deploy/osd.py
Fixes http://tracker.ceph.com/issues/17086
> [RM-17086] osd: use load_raw for reading/writing ceph conf

- ceph_deploy/hosts/centos/__init__.py
- ceph_deploy/hosts/rhel/__init__.py
See: http://tracker.ceph.com/issues/17107
> better systemd/sysvinit checks for CentOS and RHEL

- ceph_deploy/gatherkeys.py
In case the key already exists but the caps do not match
See: http://tracker.ceph.com/issues/16443
> [RM-16443] gatherkeys: try getting an existing key without caps

- ceph_deploy/gatherkeys.py
See: http://tracker.ceph.com/issues/17823
> [RM-17823] gatherkeys: add missing argument to log call

- ceph_deploy/hosts/__init__.py
- ceph_deploy/hosts/centos/install.py
- ceph_deploy/hosts/remotes.py
- ceph_deploy/tests/unit/hosts/test_hosts.py
I need support oracle linux server.
I use oracle linux server for use support oracle software.
https://en.wikipedia.org/wiki/Oracle_Linux
> [RM-17612] Support oracle linux server

- ceph_deploy/hosts/remotes.py
> [RM-18410] In python3, bytes should be decoded first

- ceph_deploy/gatherkeys.py
> gatherkeys: mgr 'allow *'

- ceph_deploy/osd.py
add the opportunity to specify block.db and block.wal in bluestore
> [RM-19266] add the opportunity to specify block.db and block.wal

- ceph_deploy/cli.py
- tox.ini
> [RM-20387] tests: test against py35

- ceph_deploy/osd.py
Fixes http://tracker.ceph.com/issues/20521
> [RM-20521] osd: add missing --filestore flag for prepare

- ceph_deploy/hosts/remotes.py
Add support to deploy on debian 9 &10
> [RM-20560] Support deploy on Debian 9 stretch

- ceph_deploy/osd.py
> [RM-20521] osd: add filestore flag in the prepare parser

- ceph_deploy/hosts/centos/install.py
Fixes: http://tracker.ceph.com/issues/20809
> [RM-20809] handle package conflicts when upgrading/reinstalling

- ceph_deploy/osd.py
Fixes: http://tracker.ceph.com/issues/22324
> enable debug mode for ceph-volume

- ceph_deploy/osd.py
- ceph_deploy/tests/parser/test_disk.py
Resolves https://tracker.ceph.com/issues/22871.
Signed-off-by: Ryan Leimenstoll <rleimens@umiacs.umd.edu>
> add debug arg to parser for disk zap

- ceph_deploy/util/net.py
When using ceph-deploy it will now also show the IPv6 addresses
it found for a node:
<pre>IP addresses found: [u'192.168.153.10', u'2001:db8::100', u'10.0.2.15']</pre>
The resulting ceph.conf will use IPv6 addresses for the Monitors:
<pre>
ms_bind_ipv6 = true
mon_host = [2001:db8::100],[2001:db8::101],[2001:db8::102]
</pre>
> net: Return both IPv4 and IPv6 addresses

- ceph_deploy/hosts/remotes.py
- ceph_deploy/tests/unit/hosts/test_remotes.py
Fixes: http://tracker.ceph.com/issues/21677
> do not consider directories as executable paths

- ceph_deploy/hosts/debian/install.py
fixes http://tracker.ceph.com/issues/19125
> [RM-19125] run apt-get update before debian installs

- ceph_deploy/install.py
Fixes http://tracker.ceph.com/issues/23190
> [RM-23190] install default to luminous

- ceph_deploy/hosts/remotes.py
I'm not sure what changed in Arch in the last 2 months since my last commit, but it's an easy fix :)
> [RM-23534] Fix distro detection for Arch Linux

- ceph_deploy/tests/test_remotes.py
- ceph_deploy/tests/unit/hosts/test_altlinux.py
- ceph_deploy/tests/unit/hosts/test_hosts.py
- ceph_deploy/tests/unit/util/test_pkg_managers.py
Was added tests ALT Linux platform for pull request #472, enough it's tests?
> Tests altlinux platform for pull request #472

- ceph_deploy/tests/test_mon.py
- ceph_deploy/util/ssh.py
> util: use 'true' when testing ssh connections

- bootstrap
> upgrade setuptools first and install rest of the dependencies later

- ceph_deploy/gatherkeys.py
- ceph_deploy/mon.py
- ceph_deploy/osd.py
- ceph_deploy/tests/test_gather_keys_missing.py
- ceph_deploy/tests/test_gather_keys_with_mon.py
- ceph_deploy/tests/test_mon.py
- ceph_deploy/util/__init__.py
- ceph_deploy/util/net.py
- setup.py
- tox.ini
Fixes http://tracker.ceph.com/issues/39489
And removes the bytes handling that is already done by remoto
> Fix bytes decoding

- debian/control
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> debian/control: add missing ","

- bootstrap
Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>
> bootstrap: support python3-virtualenv on ubuntu

- setup.py
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
> setup: Install configparser when running on py2

- ceph_deploy/hosts/__init__.py
Add support for openEuler OS
Signed-off-by: Dai zhiwei daizhiwei3@huawei.com
> Add support for openEuler OS

- docs/source/conf.py
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> doc: import ceph_deploy from ../..
